const products = [
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: '/images/airpods.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly. High-quality AAC audio offers immersive listening experience. Built-in microphone allows you to take calls while working.',
    brand: 'Apple',
    category: 'Electronics',
    price: 89.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'iPhone 15 Pro 256GB Memory',
    image: '/images/airpods.jpg',
    description:
      'Experience blazing performance with the A17 Pro chip and Dynamic Island display. Features 48MP camera and titanium design.',
    brand: 'Apple',
    category: 'Electronics',
    price: 1199.99,
    countInStock: 7,
    rating: 4.8,
    numReviews: 25,
  },
  {
    _id: '3',
    name: 'Samsung Galaxy S24 Ultra 512GB',
    image: '/images/airpods.jpg',
    description:
      'Latest flagship from Samsung featuring an advanced AI camera, S-Pen, and Snapdragon 8 Gen 3 for lightning-fast performance.',
    brand: 'Samsung',
    category: 'Electronics',
    price: 1399.99,
    countInStock: 5,
    rating: 5,
    numReviews: 30,
  },
  {
    _id: '4',
    name: 'Sony WH-1000XM5 Noise Cancelling Headphones',
    image: '/images/airpods.jpg',
    description:
      'Industry-leading noise cancellation with adaptive sound control and 30-hour battery life for uninterrupted music experience.',
    brand: 'Sony',
    category: 'Electronics',
    price: 349.99,
    countInStock: 15,
    rating: 2,
    numReviews: 60,
  },
  {
    _id: '5',
    name: 'Apple MacBook Air M3 13-inch',
    image: '/images/airpods.jpg',
    description:
      'Powered by the new M3 chip, delivering faster performance and up to 18 hours of battery life in an ultra-slim design.',
    brand: 'Apple',
    category: 'Computers',
    price: 1199.99,
    countInStock: 9,
    rating: 4.8,
    numReviews: 22,
  },
  {
    _id: '6',
    name: 'Dell XPS 15 OLED Laptop',
    image: '/images/airpods.jpg',
    description:
      'Premium 15-inch laptop with stunning 3.5K OLED touchscreen, Intel i9 processor, and NVIDIA RTX 4070 GPU.',
    brand: 'Dell',
    category: 'Computers',
    price: 1999.99,
    countInStock: 4,
    rating: 2,
    numReviews: 18,
  },
  {
       _id: '7',
    name: 'Apple Watch Ultra 2',
    image: '/images/airpods.jpg',
    description:
      'Built for adventure with titanium case, precision dual-frequency GPS, and up to 36-hour battery life.',
    brand: 'Apple',
    category: 'Wearables',
    price: 799.99,
    countInStock: 8,
    rating: 1,
    numReviews: 40,
  },
  {
    _id: '8',
    name: 'Amazon Echo Show 10 (3rd Gen)',
    image: '/images/airpods.jpg',
    description:
      'Smart display with motion tracking and Alexa built-in. Control smart home devices and enjoy video calls with auto-framing.',
    brand: 'Amazon',
    category: 'Smart Home',
    price: 249.99,
    countInStock: 12,
    rating: 4,
    numReviews: 35,
  },
  {
    _id: '9',
    name: 'Logitech MX Master 3S Wireless Mouse',
    image: '/images/airpods.jpg',
    description:
      'Ergonomic design, MagSpeed scrolling, and multi-device connectivity. Ideal for professionals and creators.',
    brand: 'Logitech',
    category: 'Accessories',
    price: 99.99,
    countInStock: 20,
    rating: 3.6,
    numReviews: 55,
  },
  {
    _id: '10',
    name: 'Razer BlackWidow V4 Pro Mechanical Keyboard',
    image: '/images/airpods.jpg',
    description:
      'High-performance mechanical keyboard with Razer Chroma RGB, dedicated media controls, and ergonomic wrist rest.',
    brand: 'Razer',
    category: 'Gaming',
    price: 229.99,
    countInStock: 14,
    rating: 3,
    numReviews: 28,
  },
];
export default products;